import type { Metadata } from "next";
import { Header } from "@/components/Header";
import { montserrat } from "@/ui/fonts";
import "@/ui/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased  px-4 lg:px-8 mx-auto`}
      >
        <Header />
        <main> {children}</main>
      </body>
    </html>
  );
}
