import type { Metadata } from "next";
import { Header } from "@/components/Header";
import { montserrat } from "@/ui/fonts";
import "@/ui/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <Header />
        <main className="w-11/12 mx-auto"> {children}</main>
      </body>
    </html>
  );
}
